#%RAML 0.8
title: BEAT_IT Example Application
version: v1_Beta
baseUri: https://api.beatit.sk

documentation:
  - title: "Popis funkčnosti jednotlivých podstránok"
    content: |
      Domovská stránka
      ------
      Domovská stránka (príklad katalógu) si načíta dáta z end-pointov `/catalog/homepage` a `/cart/info`.
      Na základe týchto dát sa vykreslí produktový katalóg a zobrazí sa náhľad košíka (V košíku máte 10 produktov za 34 eur).
      Po kliknutí na tlačidlo **Pridať do košíka** sa produkt pridá do košíka zaslaním `POST /cart/items`, následne sa aktualizuje náhľad košíka.

      Košík
      ------
      Košík si načítavá dáta pomocou `GET /cart`. Rozdelený je do troch krokov.

      1.krok
      ------
      Na prvom kroku sa zobrazuje samotný **nákupný košík** (Položky, Cena). Zároveň je zobrazená aj tabuľka **kombinácií platieb a dopravy**. (Dáta z ` GET /cart/deliverypayment`)
      Po výbere platby alebo dopravy sa aktualizuje finálna cena objednávky. Výber ceny ako aj dopravy je povinný ak sa zákazník pokúsi pokračovať
      v objednávke bez vybratia dopravy a platby je upozornený (alert).

      V prvom kroku objednávky je možné vymazať produkt z košíka pomocou `DELETE /cart/items/{id}`.

      Po kliknutí na tlačidlo **Pokračovať** je potrebné odoslať dáta košíka na uloženie `PUT /cart` - v prípade prvého kroku sa odošlú napr. dáta {"delivery" : "VYBRANE_DODANIE", "payment": "VYBRANA_PLATBA"}

      2.krok
      ------
      V druhom kroku platby sa zobrazuje formulár s informáciami o osobe, fakturačnej adrese a dodacej adrese. Všetky polia sa validujú.

      3.krok
      ------
      Tretí krok je sumarizáciou objednávky - všetky dáta sa zobrazia ešte raz. Zákazník môže definitívne potvrdiť objednávku.
  - title: "TODO"
    content: |
      1. Určiť akým spôsobom sa budú aplikácie - ich košíky identifikovať. Navrhujem v každom requeste odosielať unikátny token (napr `HEADER Authorization: 1234454567889900`) vidaný pre clientskú aplikáciu.
         V prípade potreby doplním end-point.
      2. Doplniť design aplikácie.
      3. Určiť URL adresu API.
/cart:
  put:
    description: "Uloženie objektu objednávky. Po ukončení jednotlivých krokov objednávky sa odošle iba príslušná časť
                  celého objektu. Po prvom kroku objednávky sa odošle napr. iba delivery a payment"
    body:
      application/json:
        schema: !include schemas/cart-post.schema.json
        example: |
          {
            "delivery": "SPS",
            "payment": "DOBIERKA",
            "person": {
                "first_name": "Ladislav",
                "surname": "Perduk",
                "email": "perduk@bart.sk",
                "phone": "0900900900"
              },
              "billing_address": {
                  "address": "Lomnická 22",
                  "city": "Košice",
                  "zip": "04001",
                  "country": "Slovakia",
                  "company": {
                        "name": "ZiZi s.r.o.",
                        "dic": "000000000000",
                        "ico": "000000000000",
                        "ic_dph": "SK000000000000"
                    }
              },
              "delivery_address":{
                  "address": "Lomnická 22",
                  "city": "Košice",
                  "zip": "04001",
                  "country": "Slovakia"
              }
          }
  get:
    description: "Detail košíka - obsahuje všetky informácie potrebné na vykreslenie košíka"
    responses:
      200:
        body:
          application/json:
            "schema": !include schemas/cart-response.schema.json
            example: |
              {
                "status": "OK",
                "data":{
                      "cart_items":[
                        {
                            "name": "Test produkt",
                            "image": {
                              "url": "http://.....sk/picture/...",
                              "thumbnail_url": "http://.....sk/picture/thumbnail...",
                              "catalog_url": "http://.....sk/picture/catalog..."
                            },
                            "quantity": 4,
                            "item_price": 3,
                            "total_price": 12
                        }
                      ],

                      "total_items_price": 12,
                      "delivery": "",
                      "payment": "",

                      "person": {
                          "first_name": "Ladislav",
                          "surname": "Perduk",
                          "email": "perduk@bart.sk",
                          "phone": "0900900900"
                        },
                        "billing_address": {
                            "address": "Lomnická 22",
                            "city": "Košice",
                            "zip": "04001",
                            "country": "Slovakia",
                            "company": {
                                  "name": "ZiZi s.r.o.",
                                  "dic": "000000000000",
                                  "ico": "000000000000",
                                  "ic_dph": "SK000000000000"
                              }
                        },
                        "delivery_address":{
                            "address": "Lomnická 22",
                            "city": "Košice",
                            "zip": "04001",
                            "country": "Slovakia"
                        }
                  }
              }
  /info:
    get:
      description: "Získanie rýchleho prehľadu košíka"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status" : "OK",
                  "data" : {

                        "count" : 4,
                        "price" : 20.04

                    }
                }
              schema: !include schemas/cart-info-response.schema.json
  /deliverypayment:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "OK",
                  "data":{
                        "delivery_opts":[
                            {
                                "id": "KURIER",
                                "price": 2.50
                            },
                            {
                                "id": "OSOBNY_ODBER",
                                "price": 0
                            }
                        ],
                        "payment_opts":[
                            {
                                "id": "CARD_ONLINE",
                                "price": 0
                            },
                            {
                                "id": "DOBIERKA",
                                "price": 1.50
                            }
                        ]
                    }
                }
  /items/{id}:
    uriParameters:
     id:
         displayName: Product ID
         description: ID produktu, ktorým budeme manipulovať
         type: integer
    delete:
      description: "Odstránenie produktu z košíka"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status" : "OK"
                }
              schema: !include schemas/cart-item-add-delete-response.schema.json
  /items:
    post:
      description: "Pridanie produktu do košíka"
      body:
        application/json:
          schema: !include schemas/cart-item-add.schema.json
          example: |
            {
                "quantity": 2
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status" : "OK"
                }
              schema: !include schemas/cart-item-add-delete-response.schema.json
/catalog:
  /homepage:
    get:
      description: "Načítanie produktov pre domovskú stránku eshopu"
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status" : "OK",
                  "data" : [
                     {
                       "name": "Product 1",
                       "price": 20.04,
                       "currency": "EUR",
                       "description": "Lorem ipsum dolor sit amet...",
                       "rating": 3,
                       "image":{
                            "url": "http://.....sk/picture/...",
                            "thumbnail_url": "http://.....sk/picture/thumbnail...",
                            "catalog_url": "http://.....sk/picture/catalog..."
                         }
                     },
                     {
                       "name": "Product 1",
                       "price": 20.04,
                       "currency": "EUR",
                       "description": "Lorem ipsum dolor sit amet...",
                       "rating": 3,
                       "image":{
                            "url": "http://.....sk/picture/...",
                            "thumbnail_url": "http://.....sk/picture/thumbnail...",
                            "catalog_url": "http://.....sk/picture/catalog..."
                         }
                     },
                     {
                       "name": "Product 1",
                       "price": 20.04,
                       "currency": "EUR",
                       "description": "Lorem ipsum dolor sit amet...",
                       "rating": 3,
                       "image":{
                            "url": "http://.....sk/picture/...",
                            "thumbnail_url": "http://.....sk/picture/thumbnail...",
                            "catalog_url": "http://.....sk/picture/catalog..."
                         }
                     }
                  ]
                }
              schema: !include schemas/catalog-homepage-response.sschema.json
